services:
  frontend:
    image: shinsenter/cakephp5
    container_name: WebAdaptors-CakePHP5
    environment:
      - TZ=America/Chicago
    ports:
      - 8321:80
      - 3888:3000
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/3000' || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    volumes:
      - /volume1/docker/webadapters:/app/data:rw
    restart: unless-stopped
  db:
    container_name: WebAdaptors-PostgreSQL
    image: postgres
    mem_limit: 256m
    cpu_shares: 768
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "marius_DB", "-U", "root"]
    environment:
      POSTGRES_USER: webadapters
      POSTGRES_PASSWORD: rootpass
      POSTGRES_DB: webadapters_db
    volumes:
      - /volume1/docker/webadapters:/var/lib/postgresql/data:rw
    ports:
      - 2665:5432
    restart: on-failure:5
  
  adminer:
    image: adminer:latest
    container_name: WebAdaptors-Adminer
    hostname: adminer
    mem_limit: 128m
    cpu_shares: 256
    security_opt:
      - no-new-privileges:true
    user: 1026:100
    ports:
      - 8220:8080
    restart: on-failure:5