services:
  webadapters:
    image: shinsenter/cakephp5
    container_name: 
    environment:
      - TZ=America/Chicago
    ports:
      - 8321:80
      - 3747:3000
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/3000' || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    volumes:
      - /volume1/docker/webadapters:/app/data:rw
    restart: unless-stopped
  db:
    image: mysql:8.0
    container_name: webadapters_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: webadapters_db
      MYSQL_USER: webadapters_user
      MYSQL_PASSWORD: webadapters
    volumes:
      - /volume1/docker/webadapters/db:/var/lib/mysql:rw
    ports:
      - 2578:3306
    restart: unless-stopped

      