###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
services:
  myapp-mailhog:
    image: 'mailhog/mailhog:latest'
    container_name: myapp-mailhog
    ports:
      - "8125:8025"

  myapp-mysql:
    image: 'mysql:8.0'
    container_name: myapp-mysql
    working_dir: /var/www/myapp
    volumes:
        - /volume1/docker/myapp/mysql:/var/lib/mysql
        - /volume1/docker/myapp/mysql-files:/var/lib/mysql-files
        - /volume1/docker/myapp/cakephp:/var/www/myapp
        - /volume1/docker/myapp/docker/mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - "8106:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  myapp-nginx:
    image: 'nginx:alpine'
    container_name: myapp-nginx
    working_dir: /var/www/myapp
    volumes:
        - /volume1/docker/myapp/cakephp:/var/www/myapp
        - /volume1/docker/myapp/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
     - "8180:80"
    links:
     - myapp-php-fpm

  myapp-php-fpm:
    build: ./php-fpm
    container_name: myapp-php-fpm
    working_dir: /var/www/myapp
    volumes:
      - /volume1/docker/myapp/cakephp:/var/www/myapp
      - /volume1/docker/myapp/docker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini
    links:
      - myapp-mailhog
      - myapp-mysql
