services:
  # Web server with CakePHP
  app:
    image: shinsenter/cakephp5:latest
    container_name: cakephp_app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - app_network
    restart: unless-stopped

  # MySQL database service
  db:
    image: mysql:8.4
    container_name: cakephp_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: cakephp_db
      MYSQL_USER: cakephp_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql  # Persist MySQL data
    networks:
      - app_network
    restart: unless-stopped

  # phpMyAdmin for managing MySQL database (optional)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8081:80"
    networks:
      - app_network
    restart: unless-stopped

# Docker volumes for persistent storage
volumes:
  db_data:

# Docker networks for communication between containers
networks:
  app_network:
