# Docker Compose Template for WillowCMS
# (network removed as requested)

services:
  willowcms:
    env_file:
      - ./config/.env
    image: docker.io/garzarobmdocker/willowcms:latest
    build:
      context: .
      dockerfile: docker/willowcms/Dockerfile
      args:
        UID: 501
        GID: 20
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html/
      - ./docker/willowcms/config/app/cms_app_local.php:/var/www/html/config/app_local.php
      - ./docker/willowcms/config/nginx/logs:/var/log/nginx/
    environment:
      - APP_NAME=${APP_NAME}
      - DEBUG=${DEBUG}
      - APP_ENCODING=${APP_ENCODING}
      - APP_DEFAULT_LOCALE=${APP_DEFAULT_LOCALE}
      - APP_DEFAULT_TIMEZONE=${APP_DEFAULT_TIMEZONE}
      - APP_FULL_BASE_URL=${APP_FULL_BASE_URL}
      - SECURITY_SALT=${SECURITY_SALT}
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PORT=${DB_PORT}
      - TEST_DB_HOST=${TEST_DB_HOST}
      - TEST_DB_USERNAME=${TEST_DB_USERNAME}
      - TEST_DB_PASSWORD=${TEST_DB_PASSWORD}
      - TEST_DB_DATABASE=${TEST_DB_DATABASE}
      - TEST_DB_PORT=${TEST_DB_PORT}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_TIMEOUT=${EMAIL_TIMEOUT}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_REPLY=${EMAIL_REPLY}
      - EMAIL_NOREPLY=${EMAIL_NOREPLY}
      - REDIS_USERNAME=${REDIS_USERNAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DATABASE=${REDIS_DATABASE}
      - REDIS_URL=${REDIS_URL}
      - REDIS_TEST_URL=${REDIS_TEST_URL}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - TRANSLATE_API_KEY=${TRANSLATE_API_KEY}
      - QUEUE_DEFAULT_URL=${QUEUE_DEFAULT_URL}
      - QUEUE_TEST_URL=${QUEUE_TEST_URL}
      - WILLOW_ADMIN_USERNAME=${WILLOW_ADMIN_USERNAME}
      - WILLOW_ADMIN_PASSWORD=${WILLOW_ADMIN_PASSWORD}
      - WILLOW_ADMIN_EMAIL=${WILLOW_ADMIN_EMAIL}
      - EXPERIMENTAL_TESTS=${EXPERIMENTAL_TESTS}

  mysql:
    env_file:
      - ./config/.env
    image: mysql:8.4.3
    environment:
      - DB_HOST=${DB_HOST}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
    ports:
      - "3310:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    env_file:
      - ./config/.env
    image: phpmyadmin
    ports:
      - 8082:80
    environment:
      - PMA_HOST=${PMA_HOST}
      - PMA_USER=${PMA_USER}
      - PMA_PASSWORD=${PMA_PASSWORD}
      - UPLOAD_LIMIT=${UPLOAD_LIMIT}

  jenkins:
    env_file:
      - ./config/.env
    image: docker.io/garzarobmdocker/jenkins:latest
    build:
      context: .
      dockerfile: docker/jenkins/Dockerfile
    privileged: true
    user: root
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/jenkins/jenkins.yaml:/var/jenkins_home/jenkins.yaml
    environment:
      - JAVA_OPTS=${JAVA_OPTS}

  mailpit:
    env_file:
      - ./config/.env
    image: axllent/mailpit:latest
    ports:
      - "1125:1025"
      - "8025:8025"
    volumes:
      - mailpit_data:/data
    environment:
      - MP_MAX_MESSAGES=${MP_MAX_MESSAGES}
      - MP_DATABASE=${MP_DATABASE}
      - MP_SMTP_AUTH_ACCEPT_ANY=${MP_SMTP_AUTH_ACCEPT_ANY}
      - MP_SMTP_AUTH_ALLOW_INSECURE=${MP_SMTP_AUTH_ALLOW_INSECURE}

  rediscommander:
    env_file:
      - ./config/.env
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USERNAME=${REDIS_USERNAME}
      - HTTP_USER=${HTTP_USER}
      - HTTP_PASSWORD=${HTTP_PASSWORD}
    ports:
      - "8084:8081"
    depends_on:
      - willowcms

volumes:
  mysql_data:
  redis_data:
  rabbitmq_data:
  jenkins_home:
  mailpit_data:
