services:
  frontend:
    image: shinsenter/cakephp5
    container_name: WebAdaptors-CakePHP5
    environment:
      - TZ=America/Chicago
    ports:
      - 8321:80
      - 3888:3000
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/3000' || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    volumes:
      - /volume1/docker/whatismyadapter-willow:/app/data:rw
    restart: unless-stopped
  # jupyter:
  #   container_name: WebAdaptors-Jupyter
  #   image: jupyter/datascience-notebook:latest
  #   mem_limit: 3g
  #   cpu_shares: 768
  #   security_opt:
  #     - no-new-privileges:true
  #   volumes:
  #     - /volume1/docker/whatismyadapter-willow/jupyter:/home/jovyan/work:rw
  #   ports:
  #     - 10235:8888
  #   restart: on-failure:5
  db:
    container_name: Whatismyadapter-Willow-PostgreSQL
    image: postgres
    mem_limit: 256m
    cpu_shares: 768
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "marius_DB", "-U", "root"]
    environment:
      POSTGRES_USER: whatismyadapter-willow
      POSTGRES_PASSWORD: rootpass
      POSTGRES_DB: whatismyadapter_willow_db
    volumes:
      - /volume1/docker/whatismyadapter-willow:/var/lib/postgresql/data:rw
    ports:
      - 2665:5432
    restart: on-failure:5
  
  adminer:
    image: adminer:latest
    container_name: WebAdaptors-Adminer
    hostname: adminer
    mem_limit: 128m
    cpu_shares: 256
    security_opt:
      - no-new-privileges:true
    user: 1026:100
    ports:
      - 8220:8080
    restart: on-failure:5
