services:
  cakephp:
    image: shinsenter/cakephp5:latest
    container_name: WebAdaptors-CakePHP5
    hostname: WebAdaptors-CakePHP5
    restart: unless-stopped
    environment:
      - TZ=America/Chicago
    ports:
      - 8323:80
      - 3888:3000
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/3000' || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    volumes:
      - /volume1/docker/webadapters/cakephp:/app/data:rw
    security_opt:
      - no-new-privileges:true
    depends_on:
      - db_postgresql
      - db_mariadb
      - redis
      - adminer

  db_mariadb:
    image: mariadb:11.4-noble
    container_name: WebAdaptors-DB
    user: 1026:100
    hostname: webadapters-db
    environment:
      DB_DATABASE: webadapters_db
      DB_USER: robjects
      DB_PASSWORD: assHIgai1!?
      DB_ROOT_PASSWORD: rootpass
      TZ: America/Chicago
    volumes:
      - /volume1/docker/webadapters/db_mariadb:/var/lib/mysql:rw
    restart: on-failure:5

  db_postgresql:
    container_name: WebAdaptors-PostgreSQL
    image: postgres
    mem_limit: 256m
    cpu_shares: 768
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "marius_DB", "-U", "root"]
    environment:
      POSTGRES_USER: robjects
      POSTGRES_PASSWORD: assHIgai1!?
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=en_US.UTF-8"
      TZ: America/Chicago
      POSTGRES_DB: webadapters_db
    hostname: WebAdaptors-PostgreSQL
    user: 1026:100
    security_opt:
      - no-new-privileges:true
    volumes:
      - /volume1/docker/webadapters/db_postgresql:/var/lib/postgresql/data:rw
    ports:
      - 2665:5432
    restart: on-failure:5
    depends_on:
      - redis

  adminer:
    image: adminer:latest
    container_name: WebAdaptors-Adminer
    hostname: adminer:latest
    security_opt:
      - no-new-privileges:true
    user: 1026:100
    ports:
      - 8443:8080
    restart: on-failure:5
    depends_on:
      - db_postgresql
      - db_mariadb
      - redis
    environment:
      - ADMINER_DEFAULT_SERVER=db_postgresql
      - ADMINER_DEFAULT_SERVER_POSTGRES=db_postgresql
      - ADMINER_DEFAULT_SERVER_REDIS=redis
      - ADMINER_DEFAULT_DB=webadapters_db
      - ADMINER_DEFAULT_USER=robjects
      - ADMINER_DEFAULT_PASSWORD=assHIgai1!?
      - TZ=America/Chicago
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s

  redis:
    image: redis
    hostname: WebAdaptors-redis
    container_name: WebAdaptors-REDIS
    user: 1026:100
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
    volumes:
      - /volume1/docker/webadapters/redis:/data:rw
    environment:
      TZ: America/Chicago

volumes:
  db_postgresql:
    driver: local
    driver_opts:
      device: /volume1/docker/webadapters/db_postgresql
      o: bind
  db_mariadb:
    driver: local
    driver_opts:
      device: /volume1/docker/webadapters/db_mariadb
      o: bind
  cakephp_data:
    driver: local
    driver_opts:
      device: /volume1/docker/webadapters/cakephp
      o: bind
  redis_data:
    driver: local
    driver_opts:
      device: /volume1/docker/webadapters/redis
      o: bind
  adminer_data:
    driver: local
    driver_opts:
      device: /volume1/docker/webadapters/adminer
      o: bind
  backend_data:
    driver: local
    driver_opts:
      device: /volume1/docker/webadapters/backend
      o: bind
  jupyter_data:
    driver: local
    driver_opts:
      device: /volume1/docker/webadapters/jupyter
      o: bind
