apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5kaWdpdGFsb2NlYW4uY29tIjp7ImF1dGgiOiJaR2xuYVhSaGJHOWpaV0Z1TG05d2NISmxjM05sWkRBek9FQndZWE56YldGcGJDNXVaWFE2Wkc5d1gzWXhYelEwTm1VelpHTTVZbVk0T0RSallURmxNRFEyWVRkalpEQTFPV1ZrWmpFMk9EVmlZemsxTVRKa1l6WTNaamN3TW1Rek0yRXpabU5rTTJFek5UYzRNak09In19fQ==
kind: Secret
metadata:
  annotations:
    digitalocean.com/dosecret-identifier: registry-whatismyadapter
  creationTimestamp: null
  name: registry-whatismyadapter
  namespace: willowcms
type: kubernetes.io/dockerconfigjson
